package com.ncu.graduation.model;

public class ExamGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_group.id
     *
     * @mbg.generated Tue May 12 21:57:39 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_group.group_num
     *
     * @mbg.generated Tue May 12 21:57:39 CST 2020
     */
    private Integer groupNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_group.leader_no
     *
     * @mbg.generated Tue May 12 21:57:39 CST 2020
     */
    private String leaderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_group.member_no
     *
     * @mbg.generated Tue May 12 21:57:39 CST 2020
     */
    private String memberNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_group.school_year
     *
     * @mbg.generated Tue May 12 21:57:39 CST 2020
     */
    private String schoolYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_group.college
     *
     * @mbg.generated Tue May 12 21:57:39 CST 2020
     */
    private String college;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_group.id
     *
     * @return the value of exam_group.id
     *
     * @mbg.generated Tue May 12 21:57:39 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_group.id
     *
     * @param id the value for exam_group.id
     *
     * @mbg.generated Tue May 12 21:57:39 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_group.group_num
     *
     * @return the value of exam_group.group_num
     *
     * @mbg.generated Tue May 12 21:57:39 CST 2020
     */
    public Integer getGroupNum() {
        return groupNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_group.group_num
     *
     * @param groupNum the value for exam_group.group_num
     *
     * @mbg.generated Tue May 12 21:57:39 CST 2020
     */
    public void setGroupNum(Integer groupNum) {
        this.groupNum = groupNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_group.leader_no
     *
     * @return the value of exam_group.leader_no
     *
     * @mbg.generated Tue May 12 21:57:39 CST 2020
     */
    public String getLeaderNo() {
        return leaderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_group.leader_no
     *
     * @param leaderNo the value for exam_group.leader_no
     *
     * @mbg.generated Tue May 12 21:57:39 CST 2020
     */
    public void setLeaderNo(String leaderNo) {
        this.leaderNo = leaderNo == null ? null : leaderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_group.member_no
     *
     * @return the value of exam_group.member_no
     *
     * @mbg.generated Tue May 12 21:57:39 CST 2020
     */
    public String getMemberNo() {
        return memberNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_group.member_no
     *
     * @param memberNo the value for exam_group.member_no
     *
     * @mbg.generated Tue May 12 21:57:39 CST 2020
     */
    public void setMemberNo(String memberNo) {
        this.memberNo = memberNo == null ? null : memberNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_group.school_year
     *
     * @return the value of exam_group.school_year
     *
     * @mbg.generated Tue May 12 21:57:39 CST 2020
     */
    public String getSchoolYear() {
        return schoolYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_group.school_year
     *
     * @param schoolYear the value for exam_group.school_year
     *
     * @mbg.generated Tue May 12 21:57:39 CST 2020
     */
    public void setSchoolYear(String schoolYear) {
        this.schoolYear = schoolYear == null ? null : schoolYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_group.college
     *
     * @return the value of exam_group.college
     *
     * @mbg.generated Tue May 12 21:57:39 CST 2020
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_group.college
     *
     * @param college the value for exam_group.college
     *
     * @mbg.generated Tue May 12 21:57:39 CST 2020
     */
    public void setCollege(String college) {
        this.college = college == null ? null : college.trim();
    }
}