package com.ncu.graduation.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProjectApplyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_apply
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_apply
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_apply
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_apply
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    public ProjectApplyExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_apply
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_apply
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_apply
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_apply
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_apply
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_apply
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_apply
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_apply
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_apply
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_apply
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_apply
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPnoIsNull() {
            addCriterion("pno is null");
            return (Criteria) this;
        }

        public Criteria andPnoIsNotNull() {
            addCriterion("pno is not null");
            return (Criteria) this;
        }

        public Criteria andPnoEqualTo(String value) {
            addCriterion("pno =", value, "pno");
            return (Criteria) this;
        }

        public Criteria andPnoNotEqualTo(String value) {
            addCriterion("pno <>", value, "pno");
            return (Criteria) this;
        }

        public Criteria andPnoGreaterThan(String value) {
            addCriterion("pno >", value, "pno");
            return (Criteria) this;
        }

        public Criteria andPnoGreaterThanOrEqualTo(String value) {
            addCriterion("pno >=", value, "pno");
            return (Criteria) this;
        }

        public Criteria andPnoLessThan(String value) {
            addCriterion("pno <", value, "pno");
            return (Criteria) this;
        }

        public Criteria andPnoLessThanOrEqualTo(String value) {
            addCriterion("pno <=", value, "pno");
            return (Criteria) this;
        }

        public Criteria andPnoLike(String value) {
            addCriterion("pno like", value, "pno");
            return (Criteria) this;
        }

        public Criteria andPnoNotLike(String value) {
            addCriterion("pno not like", value, "pno");
            return (Criteria) this;
        }

        public Criteria andPnoIn(List<String> values) {
            addCriterion("pno in", values, "pno");
            return (Criteria) this;
        }

        public Criteria andPnoNotIn(List<String> values) {
            addCriterion("pno not in", values, "pno");
            return (Criteria) this;
        }

        public Criteria andPnoBetween(String value1, String value2) {
            addCriterion("pno between", value1, value2, "pno");
            return (Criteria) this;
        }

        public Criteria andPnoNotBetween(String value1, String value2) {
            addCriterion("pno not between", value1, value2, "pno");
            return (Criteria) this;
        }

        public Criteria andPnameIsNull() {
            addCriterion("pname is null");
            return (Criteria) this;
        }

        public Criteria andPnameIsNotNull() {
            addCriterion("pname is not null");
            return (Criteria) this;
        }

        public Criteria andPnameEqualTo(String value) {
            addCriterion("pname =", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameNotEqualTo(String value) {
            addCriterion("pname <>", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameGreaterThan(String value) {
            addCriterion("pname >", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameGreaterThanOrEqualTo(String value) {
            addCriterion("pname >=", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameLessThan(String value) {
            addCriterion("pname <", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameLessThanOrEqualTo(String value) {
            addCriterion("pname <=", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameLike(String value) {
            addCriterion("pname like", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameNotLike(String value) {
            addCriterion("pname not like", value, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameIn(List<String> values) {
            addCriterion("pname in", values, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameNotIn(List<String> values) {
            addCriterion("pname not in", values, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameBetween(String value1, String value2) {
            addCriterion("pname between", value1, value2, "pname");
            return (Criteria) this;
        }

        public Criteria andPnameNotBetween(String value1, String value2) {
            addCriterion("pname not between", value1, value2, "pname");
            return (Criteria) this;
        }

        public Criteria andFilePathIsNull() {
            addCriterion("file_path is null");
            return (Criteria) this;
        }

        public Criteria andFilePathIsNotNull() {
            addCriterion("file_path is not null");
            return (Criteria) this;
        }

        public Criteria andFilePathEqualTo(String value) {
            addCriterion("file_path =", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotEqualTo(String value) {
            addCriterion("file_path <>", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathGreaterThan(String value) {
            addCriterion("file_path >", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathGreaterThanOrEqualTo(String value) {
            addCriterion("file_path >=", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLessThan(String value) {
            addCriterion("file_path <", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLessThanOrEqualTo(String value) {
            addCriterion("file_path <=", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathLike(String value) {
            addCriterion("file_path like", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotLike(String value) {
            addCriterion("file_path not like", value, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathIn(List<String> values) {
            addCriterion("file_path in", values, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotIn(List<String> values) {
            addCriterion("file_path not in", values, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathBetween(String value1, String value2) {
            addCriterion("file_path between", value1, value2, "filePath");
            return (Criteria) this;
        }

        public Criteria andFilePathNotBetween(String value1, String value2) {
            addCriterion("file_path not between", value1, value2, "filePath");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTagsIsNull() {
            addCriterion("tags is null");
            return (Criteria) this;
        }

        public Criteria andTagsIsNotNull() {
            addCriterion("tags is not null");
            return (Criteria) this;
        }

        public Criteria andTagsEqualTo(String value) {
            addCriterion("tags =", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotEqualTo(String value) {
            addCriterion("tags <>", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThan(String value) {
            addCriterion("tags >", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsGreaterThanOrEqualTo(String value) {
            addCriterion("tags >=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThan(String value) {
            addCriterion("tags <", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLessThanOrEqualTo(String value) {
            addCriterion("tags <=", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsLike(String value) {
            addCriterion("tags like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotLike(String value) {
            addCriterion("tags not like", value, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsIn(List<String> values) {
            addCriterion("tags in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotIn(List<String> values) {
            addCriterion("tags not in", values, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsBetween(String value1, String value2) {
            addCriterion("tags between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andTagsNotBetween(String value1, String value2) {
            addCriterion("tags not between", value1, value2, "tags");
            return (Criteria) this;
        }

        public Criteria andCollegeIsNull() {
            addCriterion("college is null");
            return (Criteria) this;
        }

        public Criteria andCollegeIsNotNull() {
            addCriterion("college is not null");
            return (Criteria) this;
        }

        public Criteria andCollegeEqualTo(String value) {
            addCriterion("college =", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeNotEqualTo(String value) {
            addCriterion("college <>", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeGreaterThan(String value) {
            addCriterion("college >", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeGreaterThanOrEqualTo(String value) {
            addCriterion("college >=", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeLessThan(String value) {
            addCriterion("college <", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeLessThanOrEqualTo(String value) {
            addCriterion("college <=", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeLike(String value) {
            addCriterion("college like", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeNotLike(String value) {
            addCriterion("college not like", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeIn(List<String> values) {
            addCriterion("college in", values, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeNotIn(List<String> values) {
            addCriterion("college not in", values, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeBetween(String value1, String value2) {
            addCriterion("college between", value1, value2, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeNotBetween(String value1, String value2) {
            addCriterion("college not between", value1, value2, "college");
            return (Criteria) this;
        }

        public Criteria andCreatorNoIsNull() {
            addCriterion("creator_no is null");
            return (Criteria) this;
        }

        public Criteria andCreatorNoIsNotNull() {
            addCriterion("creator_no is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorNoEqualTo(String value) {
            addCriterion("creator_no =", value, "creatorNo");
            return (Criteria) this;
        }

        public Criteria andCreatorNoNotEqualTo(String value) {
            addCriterion("creator_no <>", value, "creatorNo");
            return (Criteria) this;
        }

        public Criteria andCreatorNoGreaterThan(String value) {
            addCriterion("creator_no >", value, "creatorNo");
            return (Criteria) this;
        }

        public Criteria andCreatorNoGreaterThanOrEqualTo(String value) {
            addCriterion("creator_no >=", value, "creatorNo");
            return (Criteria) this;
        }

        public Criteria andCreatorNoLessThan(String value) {
            addCriterion("creator_no <", value, "creatorNo");
            return (Criteria) this;
        }

        public Criteria andCreatorNoLessThanOrEqualTo(String value) {
            addCriterion("creator_no <=", value, "creatorNo");
            return (Criteria) this;
        }

        public Criteria andCreatorNoLike(String value) {
            addCriterion("creator_no like", value, "creatorNo");
            return (Criteria) this;
        }

        public Criteria andCreatorNoNotLike(String value) {
            addCriterion("creator_no not like", value, "creatorNo");
            return (Criteria) this;
        }

        public Criteria andCreatorNoIn(List<String> values) {
            addCriterion("creator_no in", values, "creatorNo");
            return (Criteria) this;
        }

        public Criteria andCreatorNoNotIn(List<String> values) {
            addCriterion("creator_no not in", values, "creatorNo");
            return (Criteria) this;
        }

        public Criteria andCreatorNoBetween(String value1, String value2) {
            addCriterion("creator_no between", value1, value2, "creatorNo");
            return (Criteria) this;
        }

        public Criteria andCreatorNoNotBetween(String value1, String value2) {
            addCriterion("creator_no not between", value1, value2, "creatorNo");
            return (Criteria) this;
        }

        public Criteria andCreatorNameIsNull() {
            addCriterion("creator_name is null");
            return (Criteria) this;
        }

        public Criteria andCreatorNameIsNotNull() {
            addCriterion("creator_name is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorNameEqualTo(String value) {
            addCriterion("creator_name =", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameNotEqualTo(String value) {
            addCriterion("creator_name <>", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameGreaterThan(String value) {
            addCriterion("creator_name >", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameGreaterThanOrEqualTo(String value) {
            addCriterion("creator_name >=", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameLessThan(String value) {
            addCriterion("creator_name <", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameLessThanOrEqualTo(String value) {
            addCriterion("creator_name <=", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameLike(String value) {
            addCriterion("creator_name like", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameNotLike(String value) {
            addCriterion("creator_name not like", value, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameIn(List<String> values) {
            addCriterion("creator_name in", values, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameNotIn(List<String> values) {
            addCriterion("creator_name not in", values, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameBetween(String value1, String value2) {
            addCriterion("creator_name between", value1, value2, "creatorName");
            return (Criteria) this;
        }

        public Criteria andCreatorNameNotBetween(String value1, String value2) {
            addCriterion("creator_name not between", value1, value2, "creatorName");
            return (Criteria) this;
        }

        public Criteria andIsPassIsNull() {
            addCriterion("is_pass is null");
            return (Criteria) this;
        }

        public Criteria andIsPassIsNotNull() {
            addCriterion("is_pass is not null");
            return (Criteria) this;
        }

        public Criteria andIsPassEqualTo(Byte value) {
            addCriterion("is_pass =", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassNotEqualTo(Byte value) {
            addCriterion("is_pass <>", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassGreaterThan(Byte value) {
            addCriterion("is_pass >", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_pass >=", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassLessThan(Byte value) {
            addCriterion("is_pass <", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassLessThanOrEqualTo(Byte value) {
            addCriterion("is_pass <=", value, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassIn(List<Byte> values) {
            addCriterion("is_pass in", values, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassNotIn(List<Byte> values) {
            addCriterion("is_pass not in", values, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassBetween(Byte value1, Byte value2) {
            addCriterion("is_pass between", value1, value2, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsPassNotBetween(Byte value1, Byte value2) {
            addCriterion("is_pass not between", value1, value2, "isPass");
            return (Criteria) this;
        }

        public Criteria andIsSelectIsNull() {
            addCriterion("is_select is null");
            return (Criteria) this;
        }

        public Criteria andIsSelectIsNotNull() {
            addCriterion("is_select is not null");
            return (Criteria) this;
        }

        public Criteria andIsSelectEqualTo(Byte value) {
            addCriterion("is_select =", value, "isSelect");
            return (Criteria) this;
        }

        public Criteria andIsSelectNotEqualTo(Byte value) {
            addCriterion("is_select <>", value, "isSelect");
            return (Criteria) this;
        }

        public Criteria andIsSelectGreaterThan(Byte value) {
            addCriterion("is_select >", value, "isSelect");
            return (Criteria) this;
        }

        public Criteria andIsSelectGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_select >=", value, "isSelect");
            return (Criteria) this;
        }

        public Criteria andIsSelectLessThan(Byte value) {
            addCriterion("is_select <", value, "isSelect");
            return (Criteria) this;
        }

        public Criteria andIsSelectLessThanOrEqualTo(Byte value) {
            addCriterion("is_select <=", value, "isSelect");
            return (Criteria) this;
        }

        public Criteria andIsSelectIn(List<Byte> values) {
            addCriterion("is_select in", values, "isSelect");
            return (Criteria) this;
        }

        public Criteria andIsSelectNotIn(List<Byte> values) {
            addCriterion("is_select not in", values, "isSelect");
            return (Criteria) this;
        }

        public Criteria andIsSelectBetween(Byte value1, Byte value2) {
            addCriterion("is_select between", value1, value2, "isSelect");
            return (Criteria) this;
        }

        public Criteria andIsSelectNotBetween(Byte value1, Byte value2) {
            addCriterion("is_select not between", value1, value2, "isSelect");
            return (Criteria) this;
        }

        public Criteria andBlindTrialNoIsNull() {
            addCriterion("blind_trial_no is null");
            return (Criteria) this;
        }

        public Criteria andBlindTrialNoIsNotNull() {
            addCriterion("blind_trial_no is not null");
            return (Criteria) this;
        }

        public Criteria andBlindTrialNoEqualTo(String value) {
            addCriterion("blind_trial_no =", value, "blindTrialNo");
            return (Criteria) this;
        }

        public Criteria andBlindTrialNoNotEqualTo(String value) {
            addCriterion("blind_trial_no <>", value, "blindTrialNo");
            return (Criteria) this;
        }

        public Criteria andBlindTrialNoGreaterThan(String value) {
            addCriterion("blind_trial_no >", value, "blindTrialNo");
            return (Criteria) this;
        }

        public Criteria andBlindTrialNoGreaterThanOrEqualTo(String value) {
            addCriterion("blind_trial_no >=", value, "blindTrialNo");
            return (Criteria) this;
        }

        public Criteria andBlindTrialNoLessThan(String value) {
            addCriterion("blind_trial_no <", value, "blindTrialNo");
            return (Criteria) this;
        }

        public Criteria andBlindTrialNoLessThanOrEqualTo(String value) {
            addCriterion("blind_trial_no <=", value, "blindTrialNo");
            return (Criteria) this;
        }

        public Criteria andBlindTrialNoLike(String value) {
            addCriterion("blind_trial_no like", value, "blindTrialNo");
            return (Criteria) this;
        }

        public Criteria andBlindTrialNoNotLike(String value) {
            addCriterion("blind_trial_no not like", value, "blindTrialNo");
            return (Criteria) this;
        }

        public Criteria andBlindTrialNoIn(List<String> values) {
            addCriterion("blind_trial_no in", values, "blindTrialNo");
            return (Criteria) this;
        }

        public Criteria andBlindTrialNoNotIn(List<String> values) {
            addCriterion("blind_trial_no not in", values, "blindTrialNo");
            return (Criteria) this;
        }

        public Criteria andBlindTrialNoBetween(String value1, String value2) {
            addCriterion("blind_trial_no between", value1, value2, "blindTrialNo");
            return (Criteria) this;
        }

        public Criteria andBlindTrialNoNotBetween(String value1, String value2) {
            addCriterion("blind_trial_no not between", value1, value2, "blindTrialNo");
            return (Criteria) this;
        }

        public Criteria andBlindTrialGradeIsNull() {
            addCriterion("blind_trial_grade is null");
            return (Criteria) this;
        }

        public Criteria andBlindTrialGradeIsNotNull() {
            addCriterion("blind_trial_grade is not null");
            return (Criteria) this;
        }

        public Criteria andBlindTrialGradeEqualTo(Byte value) {
            addCriterion("blind_trial_grade =", value, "blindTrialGrade");
            return (Criteria) this;
        }

        public Criteria andBlindTrialGradeNotEqualTo(Byte value) {
            addCriterion("blind_trial_grade <>", value, "blindTrialGrade");
            return (Criteria) this;
        }

        public Criteria andBlindTrialGradeGreaterThan(Byte value) {
            addCriterion("blind_trial_grade >", value, "blindTrialGrade");
            return (Criteria) this;
        }

        public Criteria andBlindTrialGradeGreaterThanOrEqualTo(Byte value) {
            addCriterion("blind_trial_grade >=", value, "blindTrialGrade");
            return (Criteria) this;
        }

        public Criteria andBlindTrialGradeLessThan(Byte value) {
            addCriterion("blind_trial_grade <", value, "blindTrialGrade");
            return (Criteria) this;
        }

        public Criteria andBlindTrialGradeLessThanOrEqualTo(Byte value) {
            addCriterion("blind_trial_grade <=", value, "blindTrialGrade");
            return (Criteria) this;
        }

        public Criteria andBlindTrialGradeIn(List<Byte> values) {
            addCriterion("blind_trial_grade in", values, "blindTrialGrade");
            return (Criteria) this;
        }

        public Criteria andBlindTrialGradeNotIn(List<Byte> values) {
            addCriterion("blind_trial_grade not in", values, "blindTrialGrade");
            return (Criteria) this;
        }

        public Criteria andBlindTrialGradeBetween(Byte value1, Byte value2) {
            addCriterion("blind_trial_grade between", value1, value2, "blindTrialGrade");
            return (Criteria) this;
        }

        public Criteria andBlindTrialGradeNotBetween(Byte value1, Byte value2) {
            addCriterion("blind_trial_grade not between", value1, value2, "blindTrialGrade");
            return (Criteria) this;
        }

        public Criteria andBlindTrialCommentIsNull() {
            addCriterion("blind_trial_comment is null");
            return (Criteria) this;
        }

        public Criteria andBlindTrialCommentIsNotNull() {
            addCriterion("blind_trial_comment is not null");
            return (Criteria) this;
        }

        public Criteria andBlindTrialCommentEqualTo(String value) {
            addCriterion("blind_trial_comment =", value, "blindTrialComment");
            return (Criteria) this;
        }

        public Criteria andBlindTrialCommentNotEqualTo(String value) {
            addCriterion("blind_trial_comment <>", value, "blindTrialComment");
            return (Criteria) this;
        }

        public Criteria andBlindTrialCommentGreaterThan(String value) {
            addCriterion("blind_trial_comment >", value, "blindTrialComment");
            return (Criteria) this;
        }

        public Criteria andBlindTrialCommentGreaterThanOrEqualTo(String value) {
            addCriterion("blind_trial_comment >=", value, "blindTrialComment");
            return (Criteria) this;
        }

        public Criteria andBlindTrialCommentLessThan(String value) {
            addCriterion("blind_trial_comment <", value, "blindTrialComment");
            return (Criteria) this;
        }

        public Criteria andBlindTrialCommentLessThanOrEqualTo(String value) {
            addCriterion("blind_trial_comment <=", value, "blindTrialComment");
            return (Criteria) this;
        }

        public Criteria andBlindTrialCommentLike(String value) {
            addCriterion("blind_trial_comment like", value, "blindTrialComment");
            return (Criteria) this;
        }

        public Criteria andBlindTrialCommentNotLike(String value) {
            addCriterion("blind_trial_comment not like", value, "blindTrialComment");
            return (Criteria) this;
        }

        public Criteria andBlindTrialCommentIn(List<String> values) {
            addCriterion("blind_trial_comment in", values, "blindTrialComment");
            return (Criteria) this;
        }

        public Criteria andBlindTrialCommentNotIn(List<String> values) {
            addCriterion("blind_trial_comment not in", values, "blindTrialComment");
            return (Criteria) this;
        }

        public Criteria andBlindTrialCommentBetween(String value1, String value2) {
            addCriterion("blind_trial_comment between", value1, value2, "blindTrialComment");
            return (Criteria) this;
        }

        public Criteria andBlindTrialCommentNotBetween(String value1, String value2) {
            addCriterion("blind_trial_comment not between", value1, value2, "blindTrialComment");
            return (Criteria) this;
        }

        public Criteria andTrialNoIsNull() {
            addCriterion("trial_no is null");
            return (Criteria) this;
        }

        public Criteria andTrialNoIsNotNull() {
            addCriterion("trial_no is not null");
            return (Criteria) this;
        }

        public Criteria andTrialNoEqualTo(String value) {
            addCriterion("trial_no =", value, "trialNo");
            return (Criteria) this;
        }

        public Criteria andTrialNoNotEqualTo(String value) {
            addCriterion("trial_no <>", value, "trialNo");
            return (Criteria) this;
        }

        public Criteria andTrialNoGreaterThan(String value) {
            addCriterion("trial_no >", value, "trialNo");
            return (Criteria) this;
        }

        public Criteria andTrialNoGreaterThanOrEqualTo(String value) {
            addCriterion("trial_no >=", value, "trialNo");
            return (Criteria) this;
        }

        public Criteria andTrialNoLessThan(String value) {
            addCriterion("trial_no <", value, "trialNo");
            return (Criteria) this;
        }

        public Criteria andTrialNoLessThanOrEqualTo(String value) {
            addCriterion("trial_no <=", value, "trialNo");
            return (Criteria) this;
        }

        public Criteria andTrialNoLike(String value) {
            addCriterion("trial_no like", value, "trialNo");
            return (Criteria) this;
        }

        public Criteria andTrialNoNotLike(String value) {
            addCriterion("trial_no not like", value, "trialNo");
            return (Criteria) this;
        }

        public Criteria andTrialNoIn(List<String> values) {
            addCriterion("trial_no in", values, "trialNo");
            return (Criteria) this;
        }

        public Criteria andTrialNoNotIn(List<String> values) {
            addCriterion("trial_no not in", values, "trialNo");
            return (Criteria) this;
        }

        public Criteria andTrialNoBetween(String value1, String value2) {
            addCriterion("trial_no between", value1, value2, "trialNo");
            return (Criteria) this;
        }

        public Criteria andTrialNoNotBetween(String value1, String value2) {
            addCriterion("trial_no not between", value1, value2, "trialNo");
            return (Criteria) this;
        }

        public Criteria andTrialGradeIsNull() {
            addCriterion("trial_grade is null");
            return (Criteria) this;
        }

        public Criteria andTrialGradeIsNotNull() {
            addCriterion("trial_grade is not null");
            return (Criteria) this;
        }

        public Criteria andTrialGradeEqualTo(Byte value) {
            addCriterion("trial_grade =", value, "trialGrade");
            return (Criteria) this;
        }

        public Criteria andTrialGradeNotEqualTo(Byte value) {
            addCriterion("trial_grade <>", value, "trialGrade");
            return (Criteria) this;
        }

        public Criteria andTrialGradeGreaterThan(Byte value) {
            addCriterion("trial_grade >", value, "trialGrade");
            return (Criteria) this;
        }

        public Criteria andTrialGradeGreaterThanOrEqualTo(Byte value) {
            addCriterion("trial_grade >=", value, "trialGrade");
            return (Criteria) this;
        }

        public Criteria andTrialGradeLessThan(Byte value) {
            addCriterion("trial_grade <", value, "trialGrade");
            return (Criteria) this;
        }

        public Criteria andTrialGradeLessThanOrEqualTo(Byte value) {
            addCriterion("trial_grade <=", value, "trialGrade");
            return (Criteria) this;
        }

        public Criteria andTrialGradeIn(List<Byte> values) {
            addCriterion("trial_grade in", values, "trialGrade");
            return (Criteria) this;
        }

        public Criteria andTrialGradeNotIn(List<Byte> values) {
            addCriterion("trial_grade not in", values, "trialGrade");
            return (Criteria) this;
        }

        public Criteria andTrialGradeBetween(Byte value1, Byte value2) {
            addCriterion("trial_grade between", value1, value2, "trialGrade");
            return (Criteria) this;
        }

        public Criteria andTrialGradeNotBetween(Byte value1, Byte value2) {
            addCriterion("trial_grade not between", value1, value2, "trialGrade");
            return (Criteria) this;
        }

        public Criteria andTrialCommentIsNull() {
            addCriterion("trial_comment is null");
            return (Criteria) this;
        }

        public Criteria andTrialCommentIsNotNull() {
            addCriterion("trial_comment is not null");
            return (Criteria) this;
        }

        public Criteria andTrialCommentEqualTo(String value) {
            addCriterion("trial_comment =", value, "trialComment");
            return (Criteria) this;
        }

        public Criteria andTrialCommentNotEqualTo(String value) {
            addCriterion("trial_comment <>", value, "trialComment");
            return (Criteria) this;
        }

        public Criteria andTrialCommentGreaterThan(String value) {
            addCriterion("trial_comment >", value, "trialComment");
            return (Criteria) this;
        }

        public Criteria andTrialCommentGreaterThanOrEqualTo(String value) {
            addCriterion("trial_comment >=", value, "trialComment");
            return (Criteria) this;
        }

        public Criteria andTrialCommentLessThan(String value) {
            addCriterion("trial_comment <", value, "trialComment");
            return (Criteria) this;
        }

        public Criteria andTrialCommentLessThanOrEqualTo(String value) {
            addCriterion("trial_comment <=", value, "trialComment");
            return (Criteria) this;
        }

        public Criteria andTrialCommentLike(String value) {
            addCriterion("trial_comment like", value, "trialComment");
            return (Criteria) this;
        }

        public Criteria andTrialCommentNotLike(String value) {
            addCriterion("trial_comment not like", value, "trialComment");
            return (Criteria) this;
        }

        public Criteria andTrialCommentIn(List<String> values) {
            addCriterion("trial_comment in", values, "trialComment");
            return (Criteria) this;
        }

        public Criteria andTrialCommentNotIn(List<String> values) {
            addCriterion("trial_comment not in", values, "trialComment");
            return (Criteria) this;
        }

        public Criteria andTrialCommentBetween(String value1, String value2) {
            addCriterion("trial_comment between", value1, value2, "trialComment");
            return (Criteria) this;
        }

        public Criteria andTrialCommentNotBetween(String value1, String value2) {
            addCriterion("trial_comment not between", value1, value2, "trialComment");
            return (Criteria) this;
        }

        public Criteria andSchoolYearIsNull() {
            addCriterion("school_year is null");
            return (Criteria) this;
        }

        public Criteria andSchoolYearIsNotNull() {
            addCriterion("school_year is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolYearEqualTo(String value) {
            addCriterion("school_year =", value, "schoolYear");
            return (Criteria) this;
        }

        public Criteria andSchoolYearNotEqualTo(String value) {
            addCriterion("school_year <>", value, "schoolYear");
            return (Criteria) this;
        }

        public Criteria andSchoolYearGreaterThan(String value) {
            addCriterion("school_year >", value, "schoolYear");
            return (Criteria) this;
        }

        public Criteria andSchoolYearGreaterThanOrEqualTo(String value) {
            addCriterion("school_year >=", value, "schoolYear");
            return (Criteria) this;
        }

        public Criteria andSchoolYearLessThan(String value) {
            addCriterion("school_year <", value, "schoolYear");
            return (Criteria) this;
        }

        public Criteria andSchoolYearLessThanOrEqualTo(String value) {
            addCriterion("school_year <=", value, "schoolYear");
            return (Criteria) this;
        }

        public Criteria andSchoolYearLike(String value) {
            addCriterion("school_year like", value, "schoolYear");
            return (Criteria) this;
        }

        public Criteria andSchoolYearNotLike(String value) {
            addCriterion("school_year not like", value, "schoolYear");
            return (Criteria) this;
        }

        public Criteria andSchoolYearIn(List<String> values) {
            addCriterion("school_year in", values, "schoolYear");
            return (Criteria) this;
        }

        public Criteria andSchoolYearNotIn(List<String> values) {
            addCriterion("school_year not in", values, "schoolYear");
            return (Criteria) this;
        }

        public Criteria andSchoolYearBetween(String value1, String value2) {
            addCriterion("school_year between", value1, value2, "schoolYear");
            return (Criteria) this;
        }

        public Criteria andSchoolYearNotBetween(String value1, String value2) {
            addCriterion("school_year not between", value1, value2, "schoolYear");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Byte value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Byte value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Byte value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Byte value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Byte value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Byte> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Byte> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Byte value1, Byte value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Byte value1, Byte value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_apply
     *
     * @mbg.generated do_not_delete_during_merge Sat May 09 00:13:38 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_apply
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}