package com.ncu.graduation.model;

import java.util.Date;

public class ProjectSelect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_select.id
     *
     * @mbg.generated Mon Mar 23 15:42:07 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_select.pro_no
     *
     * @mbg.generated Mon Mar 23 15:42:07 CST 2020
     */
    private String proNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_select.selector_no
     *
     * @mbg.generated Mon Mar 23 15:42:07 CST 2020
     */
    private String selectorNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_select.is_select
     *
     * @mbg.generated Mon Mar 23 15:42:07 CST 2020
     */
    private Byte isSelect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_select.gmt_create
     *
     * @mbg.generated Mon Mar 23 15:42:07 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_select.gmt_modified
     *
     * @mbg.generated Mon Mar 23 15:42:07 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_select.id
     *
     * @return the value of project_select.id
     *
     * @mbg.generated Mon Mar 23 15:42:07 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_select.id
     *
     * @param id the value for project_select.id
     *
     * @mbg.generated Mon Mar 23 15:42:07 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_select.pro_no
     *
     * @return the value of project_select.pro_no
     *
     * @mbg.generated Mon Mar 23 15:42:07 CST 2020
     */
    public String getProNo() {
        return proNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_select.pro_no
     *
     * @param proNo the value for project_select.pro_no
     *
     * @mbg.generated Mon Mar 23 15:42:07 CST 2020
     */
    public void setProNo(String proNo) {
        this.proNo = proNo == null ? null : proNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_select.selector_no
     *
     * @return the value of project_select.selector_no
     *
     * @mbg.generated Mon Mar 23 15:42:07 CST 2020
     */
    public String getSelectorNo() {
        return selectorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_select.selector_no
     *
     * @param selectorNo the value for project_select.selector_no
     *
     * @mbg.generated Mon Mar 23 15:42:07 CST 2020
     */
    public void setSelectorNo(String selectorNo) {
        this.selectorNo = selectorNo == null ? null : selectorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_select.is_select
     *
     * @return the value of project_select.is_select
     *
     * @mbg.generated Mon Mar 23 15:42:07 CST 2020
     */
    public Byte getIsSelect() {
        return isSelect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_select.is_select
     *
     * @param isSelect the value for project_select.is_select
     *
     * @mbg.generated Mon Mar 23 15:42:07 CST 2020
     */
    public void setIsSelect(Byte isSelect) {
        this.isSelect = isSelect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_select.gmt_create
     *
     * @return the value of project_select.gmt_create
     *
     * @mbg.generated Mon Mar 23 15:42:07 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_select.gmt_create
     *
     * @param gmtCreate the value for project_select.gmt_create
     *
     * @mbg.generated Mon Mar 23 15:42:07 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_select.gmt_modified
     *
     * @return the value of project_select.gmt_modified
     *
     * @mbg.generated Mon Mar 23 15:42:07 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_select.gmt_modified
     *
     * @param gmtModified the value for project_select.gmt_modified
     *
     * @mbg.generated Mon Mar 23 15:42:07 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}