package com.ncu.graduation.model;

import java.util.Date;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pno
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    private String pno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pname
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.tno
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    private String tno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.tname
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    private String tname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.sno
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    private String sno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.sname
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.school_year
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    private String schoolYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.gmt_create
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.gmt_modified
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pno
     *
     * @return the value of project.pno
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    public String getPno() {
        return pno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pno
     *
     * @param pno the value for project.pno
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    public void setPno(String pno) {
        this.pno = pno == null ? null : pno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pname
     *
     * @return the value of project.pname
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pname
     *
     * @param pname the value for project.pname
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.tno
     *
     * @return the value of project.tno
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    public String getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.tno
     *
     * @param tno the value for project.tno
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    public void setTno(String tno) {
        this.tno = tno == null ? null : tno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.tname
     *
     * @return the value of project.tname
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.tname
     *
     * @param tname the value for project.tname
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.sno
     *
     * @return the value of project.sno
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.sno
     *
     * @param sno the value for project.sno
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    public void setSno(String sno) {
        this.sno = sno == null ? null : sno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.sname
     *
     * @return the value of project.sname
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.sname
     *
     * @param sname the value for project.sname
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.school_year
     *
     * @return the value of project.school_year
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    public String getSchoolYear() {
        return schoolYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.school_year
     *
     * @param schoolYear the value for project.school_year
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    public void setSchoolYear(String schoolYear) {
        this.schoolYear = schoolYear == null ? null : schoolYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.gmt_create
     *
     * @return the value of project.gmt_create
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.gmt_create
     *
     * @param gmtCreate the value for project.gmt_create
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.gmt_modified
     *
     * @return the value of project.gmt_modified
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.gmt_modified
     *
     * @param gmtModified the value for project.gmt_modified
     *
     * @mbg.generated Mon Mar 30 23:51:39 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}