package com.ncu.graduation.model;

import java.util.Date;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.id
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tno
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    private String tno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tname
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    private String tname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.password
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.college
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    private String college;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.role
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.lead_student_num
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    private Byte leadStudentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.gmt_create
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.gmt_modified
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.group_num
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    private Integer groupNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.group_role
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    private String groupRole;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.id
     *
     * @return the value of teacher.id
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.id
     *
     * @param id the value for teacher.id
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tno
     *
     * @return the value of teacher.tno
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public String getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tno
     *
     * @param tno the value for teacher.tno
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public void setTno(String tno) {
        this.tno = tno == null ? null : tno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tname
     *
     * @return the value of teacher.tname
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tname
     *
     * @param tname the value for teacher.tname
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.password
     *
     * @return the value of teacher.password
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.password
     *
     * @param password the value for teacher.password
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.college
     *
     * @return the value of teacher.college
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.college
     *
     * @param college the value for teacher.college
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public void setCollege(String college) {
        this.college = college == null ? null : college.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.role
     *
     * @return the value of teacher.role
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.role
     *
     * @param role the value for teacher.role
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.lead_student_num
     *
     * @return the value of teacher.lead_student_num
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public Byte getLeadStudentNum() {
        return leadStudentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.lead_student_num
     *
     * @param leadStudentNum the value for teacher.lead_student_num
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public void setLeadStudentNum(Byte leadStudentNum) {
        this.leadStudentNum = leadStudentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.gmt_create
     *
     * @return the value of teacher.gmt_create
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.gmt_create
     *
     * @param gmtCreate the value for teacher.gmt_create
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.gmt_modified
     *
     * @return the value of teacher.gmt_modified
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.gmt_modified
     *
     * @param gmtModified the value for teacher.gmt_modified
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.group_num
     *
     * @return the value of teacher.group_num
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public Integer getGroupNum() {
        return groupNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.group_num
     *
     * @param groupNum the value for teacher.group_num
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public void setGroupNum(Integer groupNum) {
        this.groupNum = groupNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.group_role
     *
     * @return the value of teacher.group_role
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public String getGroupRole() {
        return groupRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.group_role
     *
     * @param groupRole the value for teacher.group_role
     *
     * @mbg.generated Fri Apr 03 22:33:14 CST 2020
     */
    public void setGroupRole(String groupRole) {
        this.groupRole = groupRole == null ? null : groupRole.trim();
    }
}