package com.ncu.graduation.model;

import java.util.Date;

public class ProjectSelect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_select.id
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_select.pno
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    private String pno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_select.pname
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_select.selector_no
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    private String selectorNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_select.selector_name
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    private String selectorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_select.is_select
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    private Byte isSelect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_select.gmt_create
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_select.gmt_modified
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_select.create_no
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    private String createNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_select.id
     *
     * @return the value of project_select.id
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_select.id
     *
     * @param id the value for project_select.id
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_select.pno
     *
     * @return the value of project_select.pno
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    public String getPno() {
        return pno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_select.pno
     *
     * @param pno the value for project_select.pno
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    public void setPno(String pno) {
        this.pno = pno == null ? null : pno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_select.pname
     *
     * @return the value of project_select.pname
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_select.pname
     *
     * @param pname the value for project_select.pname
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_select.selector_no
     *
     * @return the value of project_select.selector_no
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    public String getSelectorNo() {
        return selectorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_select.selector_no
     *
     * @param selectorNo the value for project_select.selector_no
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    public void setSelectorNo(String selectorNo) {
        this.selectorNo = selectorNo == null ? null : selectorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_select.selector_name
     *
     * @return the value of project_select.selector_name
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    public String getSelectorName() {
        return selectorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_select.selector_name
     *
     * @param selectorName the value for project_select.selector_name
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    public void setSelectorName(String selectorName) {
        this.selectorName = selectorName == null ? null : selectorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_select.is_select
     *
     * @return the value of project_select.is_select
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    public Byte getIsSelect() {
        return isSelect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_select.is_select
     *
     * @param isSelect the value for project_select.is_select
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    public void setIsSelect(Byte isSelect) {
        this.isSelect = isSelect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_select.gmt_create
     *
     * @return the value of project_select.gmt_create
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_select.gmt_create
     *
     * @param gmtCreate the value for project_select.gmt_create
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_select.gmt_modified
     *
     * @return the value of project_select.gmt_modified
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_select.gmt_modified
     *
     * @param gmtModified the value for project_select.gmt_modified
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_select.create_no
     *
     * @return the value of project_select.create_no
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    public String getCreateNo() {
        return createNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_select.create_no
     *
     * @param createNo the value for project_select.create_no
     *
     * @mbg.generated Wed Mar 25 21:42:23 CST 2020
     */
    public void setCreateNo(String createNo) {
        this.createNo = createNo == null ? null : createNo.trim();
    }
}