package com.ncu.graduation.model;

import java.util.Date;

public class ProjectApply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_apply.id
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_apply.project_no
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    private String projectNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_apply.is_pass
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    private Byte isPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_apply.blind_trial_no
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    private String blindTrialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_apply.blind_trial_grade
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    private Byte blindTrialGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_apply.blind_trial_comment
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    private String blindTrialComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_apply.trial_no
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    private String trialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_apply.trial_comment
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    private String trialComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_apply.gmt_create
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_apply.gmt_modified
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_apply.school_year
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    private String schoolYear;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_apply.id
     *
     * @return the value of project_apply.id
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_apply.id
     *
     * @param id the value for project_apply.id
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_apply.project_no
     *
     * @return the value of project_apply.project_no
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public String getProjectNo() {
        return projectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_apply.project_no
     *
     * @param projectNo the value for project_apply.project_no
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public void setProjectNo(String projectNo) {
        this.projectNo = projectNo == null ? null : projectNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_apply.is_pass
     *
     * @return the value of project_apply.is_pass
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public Byte getIsPass() {
        return isPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_apply.is_pass
     *
     * @param isPass the value for project_apply.is_pass
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public void setIsPass(Byte isPass) {
        this.isPass = isPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_apply.blind_trial_no
     *
     * @return the value of project_apply.blind_trial_no
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public String getBlindTrialNo() {
        return blindTrialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_apply.blind_trial_no
     *
     * @param blindTrialNo the value for project_apply.blind_trial_no
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public void setBlindTrialNo(String blindTrialNo) {
        this.blindTrialNo = blindTrialNo == null ? null : blindTrialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_apply.blind_trial_grade
     *
     * @return the value of project_apply.blind_trial_grade
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public Byte getBlindTrialGrade() {
        return blindTrialGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_apply.blind_trial_grade
     *
     * @param blindTrialGrade the value for project_apply.blind_trial_grade
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public void setBlindTrialGrade(Byte blindTrialGrade) {
        this.blindTrialGrade = blindTrialGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_apply.blind_trial_comment
     *
     * @return the value of project_apply.blind_trial_comment
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public String getBlindTrialComment() {
        return blindTrialComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_apply.blind_trial_comment
     *
     * @param blindTrialComment the value for project_apply.blind_trial_comment
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public void setBlindTrialComment(String blindTrialComment) {
        this.blindTrialComment = blindTrialComment == null ? null : blindTrialComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_apply.trial_no
     *
     * @return the value of project_apply.trial_no
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public String getTrialNo() {
        return trialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_apply.trial_no
     *
     * @param trialNo the value for project_apply.trial_no
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public void setTrialNo(String trialNo) {
        this.trialNo = trialNo == null ? null : trialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_apply.trial_comment
     *
     * @return the value of project_apply.trial_comment
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public String getTrialComment() {
        return trialComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_apply.trial_comment
     *
     * @param trialComment the value for project_apply.trial_comment
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public void setTrialComment(String trialComment) {
        this.trialComment = trialComment == null ? null : trialComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_apply.gmt_create
     *
     * @return the value of project_apply.gmt_create
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_apply.gmt_create
     *
     * @param gmtCreate the value for project_apply.gmt_create
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_apply.gmt_modified
     *
     * @return the value of project_apply.gmt_modified
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_apply.gmt_modified
     *
     * @param gmtModified the value for project_apply.gmt_modified
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_apply.school_year
     *
     * @return the value of project_apply.school_year
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public String getSchoolYear() {
        return schoolYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_apply.school_year
     *
     * @param schoolYear the value for project_apply.school_year
     *
     * @mbg.generated Mon Mar 16 00:23:10 CST 2020
     */
    public void setSchoolYear(String schoolYear) {
        this.schoolYear = schoolYear == null ? null : schoolYear.trim();
    }
}