package com.ncu.graduation.mapper;

import com.ncu.graduation.model.OpenReportRecord;
import com.ncu.graduation.model.OpenReportRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OpenReportRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report_record
     *
     * @mbg.generated Tue May 12 20:39:34 CST 2020
     */
    long countByExample(OpenReportRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report_record
     *
     * @mbg.generated Tue May 12 20:39:34 CST 2020
     */
    int deleteByExample(OpenReportRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report_record
     *
     * @mbg.generated Tue May 12 20:39:34 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report_record
     *
     * @mbg.generated Tue May 12 20:39:34 CST 2020
     */
    int insert(OpenReportRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report_record
     *
     * @mbg.generated Tue May 12 20:39:34 CST 2020
     */
    int insertSelective(OpenReportRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report_record
     *
     * @mbg.generated Tue May 12 20:39:34 CST 2020
     */
    List<OpenReportRecord> selectByExampleWithRowbounds(OpenReportRecordExample example,
        RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report_record
     *
     * @mbg.generated Tue May 12 20:39:34 CST 2020
     */
    List<OpenReportRecord> selectByExample(OpenReportRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report_record
     *
     * @mbg.generated Tue May 12 20:39:34 CST 2020
     */
    OpenReportRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report_record
     *
     * @mbg.generated Tue May 12 20:39:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") OpenReportRecord record,
        @Param("example") OpenReportRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report_record
     *
     * @mbg.generated Tue May 12 20:39:34 CST 2020
     */
    int updateByExample(@Param("record") OpenReportRecord record,
        @Param("example") OpenReportRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report_record
     *
     * @mbg.generated Tue May 12 20:39:34 CST 2020
     */
    int updateByPrimaryKeySelective(OpenReportRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report_record
     *
     * @mbg.generated Tue May 12 20:39:34 CST 2020
     */
    int updateByPrimaryKey(OpenReportRecord record);
}