package com.ncu.graduation.mapper;

import com.ncu.graduation.model.OralExamScore;
import com.ncu.graduation.model.OralExamScoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OralExamScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oral_exam_score
     *
     * @mbg.generated Mon Apr 20 10:53:33 CST 2020
     */
    long countByExample(OralExamScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oral_exam_score
     *
     * @mbg.generated Mon Apr 20 10:53:33 CST 2020
     */
    int deleteByExample(OralExamScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oral_exam_score
     *
     * @mbg.generated Mon Apr 20 10:53:33 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oral_exam_score
     *
     * @mbg.generated Mon Apr 20 10:53:33 CST 2020
     */
    int insert(OralExamScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oral_exam_score
     *
     * @mbg.generated Mon Apr 20 10:53:33 CST 2020
     */
    int insertSelective(OralExamScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oral_exam_score
     *
     * @mbg.generated Mon Apr 20 10:53:33 CST 2020
     */
    List<OralExamScore> selectByExampleWithRowbounds(OralExamScoreExample example,
        RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oral_exam_score
     *
     * @mbg.generated Mon Apr 20 10:53:33 CST 2020
     */
    List<OralExamScore> selectByExample(OralExamScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oral_exam_score
     *
     * @mbg.generated Mon Apr 20 10:53:33 CST 2020
     */
    OralExamScore selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oral_exam_score
     *
     * @mbg.generated Mon Apr 20 10:53:33 CST 2020
     */
    int updateByExampleSelective(@Param("record") OralExamScore record,
        @Param("example") OralExamScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oral_exam_score
     *
     * @mbg.generated Mon Apr 20 10:53:33 CST 2020
     */
    int updateByExample(@Param("record") OralExamScore record,
        @Param("example") OralExamScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oral_exam_score
     *
     * @mbg.generated Mon Apr 20 10:53:33 CST 2020
     */
    int updateByPrimaryKeySelective(OralExamScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oral_exam_score
     *
     * @mbg.generated Mon Apr 20 10:53:33 CST 2020
     */
    int updateByPrimaryKey(OralExamScore record);
}