package com.ncu.graduation.mapper;

import com.ncu.graduation.model.ForeignRecord;
import com.ncu.graduation.model.ForeignRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ForeignRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreign_record
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    long countByExample(ForeignRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreign_record
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    int deleteByExample(ForeignRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreign_record
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreign_record
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    int insert(ForeignRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreign_record
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    int insertSelective(ForeignRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreign_record
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    List<ForeignRecord> selectByExampleWithRowbounds(ForeignRecordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreign_record
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    List<ForeignRecord> selectByExample(ForeignRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreign_record
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    ForeignRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreign_record
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") ForeignRecord record, @Param("example") ForeignRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreign_record
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    int updateByExample(@Param("record") ForeignRecord record, @Param("example") ForeignRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreign_record
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    int updateByPrimaryKeySelective(ForeignRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foreign_record
     *
     * @mbg.generated Sat May 09 00:13:38 CST 2020
     */
    int updateByPrimaryKey(ForeignRecord record);
}