package com.ncu.graduation.mapper;

import com.ncu.graduation.model.GuidanceRecord;
import com.ncu.graduation.model.GuidanceRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GuidanceRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guidance_record
     *
     * @mbg.generated Thu May 07 20:10:53 CST 2020
     */
    long countByExample(GuidanceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guidance_record
     *
     * @mbg.generated Thu May 07 20:10:53 CST 2020
     */
    int deleteByExample(GuidanceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guidance_record
     *
     * @mbg.generated Thu May 07 20:10:53 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guidance_record
     *
     * @mbg.generated Thu May 07 20:10:53 CST 2020
     */
    int insert(GuidanceRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guidance_record
     *
     * @mbg.generated Thu May 07 20:10:53 CST 2020
     */
    int insertSelective(GuidanceRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guidance_record
     *
     * @mbg.generated Thu May 07 20:10:53 CST 2020
     */
    List<GuidanceRecord> selectByExampleWithRowbounds(GuidanceRecordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guidance_record
     *
     * @mbg.generated Thu May 07 20:10:53 CST 2020
     */
    List<GuidanceRecord> selectByExample(GuidanceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guidance_record
     *
     * @mbg.generated Thu May 07 20:10:53 CST 2020
     */
    GuidanceRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guidance_record
     *
     * @mbg.generated Thu May 07 20:10:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") GuidanceRecord record, @Param("example") GuidanceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guidance_record
     *
     * @mbg.generated Thu May 07 20:10:53 CST 2020
     */
    int updateByExample(@Param("record") GuidanceRecord record, @Param("example") GuidanceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guidance_record
     *
     * @mbg.generated Thu May 07 20:10:53 CST 2020
     */
    int updateByPrimaryKeySelective(GuidanceRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guidance_record
     *
     * @mbg.generated Thu May 07 20:10:53 CST 2020
     */
    int updateByPrimaryKey(GuidanceRecord record);
}