package com.ncu.graduation.mapper;

import com.ncu.graduation.model.OpenReport;
import com.ncu.graduation.model.OpenReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OpenReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report
     *
     * @mbg.generated Thu Apr 16 21:08:57 CST 2020
     */
    long countByExample(OpenReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report
     *
     * @mbg.generated Thu Apr 16 21:08:57 CST 2020
     */
    int deleteByExample(OpenReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report
     *
     * @mbg.generated Thu Apr 16 21:08:57 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report
     *
     * @mbg.generated Thu Apr 16 21:08:57 CST 2020
     */
    int insert(OpenReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report
     *
     * @mbg.generated Thu Apr 16 21:08:57 CST 2020
     */
    int insertSelective(OpenReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report
     *
     * @mbg.generated Thu Apr 16 21:08:57 CST 2020
     */
    List<OpenReport> selectByExampleWithRowbounds(OpenReportExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report
     *
     * @mbg.generated Thu Apr 16 21:08:57 CST 2020
     */
    List<OpenReport> selectByExample(OpenReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report
     *
     * @mbg.generated Thu Apr 16 21:08:57 CST 2020
     */
    OpenReport selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report
     *
     * @mbg.generated Thu Apr 16 21:08:57 CST 2020
     */
    int updateByExampleSelective(@Param("record") OpenReport record, @Param("example") OpenReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report
     *
     * @mbg.generated Thu Apr 16 21:08:57 CST 2020
     */
    int updateByExample(@Param("record") OpenReport record, @Param("example") OpenReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report
     *
     * @mbg.generated Thu Apr 16 21:08:57 CST 2020
     */
    int updateByPrimaryKeySelective(OpenReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_report
     *
     * @mbg.generated Thu Apr 16 21:08:57 CST 2020
     */
    int updateByPrimaryKey(OpenReport record);
}